version: "3.8" # Updated version
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  # Stable version (downloaded from GitHub) - Port 80
  hrms-stable:
    image: frappe/bench:latest
    command: bash /workspace/init-stable.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 80:8000
      - 9000:9000
    depends_on:
      - mariadb
      - redis

  # Development version (local HRMS code) - Port 3000
  hrms-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hrms
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 3000:8000
      - 9001:9000
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
